version: "3.9"

services:
    database_finapi:
      image: postgres
      container_name: database-finapi
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=fin_api
      volumes:
        - pgdata:/data/postgres

    app:
      build: .
      container_name: fin_api
      restart: always
      ports:
          - 3333:3333
          - 9229:9229
      volumes:
          - .:/usr/app
      links:
          - database_finapi
      depends_on:
          - database_finapi

volumes:
  pgdata:
    driver: local
